# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronograph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pid',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
